cap/cap/urls.py
import os

from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path
from django.views.generic import TemplateView
from django.views.static import serve

urlpatterns = [
    path("", include('prcr.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon
urlpatterns += [
    path('favicon.ico', serve, {
        'path': 'favicon.ico',
        'document_root': os.path.join(BASE_DIR, 'home/static')
    }),
]

cap/prcr/urls.py
from django.urls import path
from . import views

app_name = 'prcr'
urlpatterns = [
    # Category list view
    path('', views.CategoryListView.as_view(), name='main_list'),

    # Category and subcategory create views
    path('new_category', views.CategoryCreateView.as_view(), name='category_create'),
    path('category/<int:pk>/new_subcategory',
         views.SubcategoryCreateView.as_view(), name='subcategory_create'),

    # Brand create view
    path('new_brand', views.BrandCreateView.as_view(), name='brand_create'),

    # Brand list view
    path('brands', views.BrandListView.as_view(), name='brand_list'),
    # Create product from brand list view
    path('brands/<int:pk>/create_product',
         views.ProductBrandCreateView.as_view(), name='product_brand_create'),

    # Product list view
    path('subcategory/<int:pk>/products', views.ProductListView.as_view(), name='product_list'),
    # Create product from subcategory list view
    path('subcategory/<int:pk>/create_product',
         views.ProductSubcategoryCreateView.as_view(), name='product_subcategory_create'),

    # Product detail, update and add image views
    path('products/<int:pk>/detail', views.ProductDetailView.as_view(), name='product_detail'),
    path('products/<int:pk>/update', views.ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/add_image', views.ProductAddImageView.as_view(), name='product_add_image'),

    # Feature create view
    path('product/<int:pk>/new_feature', views.FeatureCreateView.as_view(), name='feature_create'),

    # Price create view
    path('product/<int:pk>/new_price', views.PriceCreateView.as_view(), name='price_create'),

    # Product picture view
    path('picture/<int:pk>', views.stream_file, name='product_picture'),

    # Comment create and delete views
    path('product/<int:pk>/comment', views.CommentCreateView.as_view(), name='comment_create'),
    path('comment/<int:pk>/delete',
         views.CommentDeleteView.as_view(), name='comment_delete'),
]

cap/prcr/models.py
from django.db import models
from django.core.validators import MinLengthValidator
# from django.contrib.auth.models import User
from django.conf import settings

# from taggit.managers import TaggableManageer # need to install and add to settings

class Category(models.Model):
    category = models.CharField(
        max_length=50,
        validators=[MinLengthValidator(2, "Category name must be longer than two letters.")],
        unique=True,
    )
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self) -> str:
        return self.category
    
    class Meta:
        verbose_name_plural = "categories"


class SubCategory(models.Model):
    subcategory = models.CharField(
        max_length=50,
        validators=[MinLengthValidator(2, "Sub-category name must be longer than two letters.")],
        unique=True,
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE,
        related_name="subcategory_category")
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self) -> str:
        return self.subcategory
    
    class Meta:
        verbose_name = "subcategory"
        verbose_name_plural = "subcategories"


class Brand(models.Model):
    brand = models.CharField(
        max_length=128,
        validators=[MinLengthValidator(2, "Brand name must be longer than two letters.")],
        unique=True,
    )
    company = models.CharField(
        max_length=128,
        validators=[MinLengthValidator(2, "Brand name must be longer than two letters.")]
    )
    class Meta:
        unique_together = ['brand', 'company']
    # add logo for upload
    # add trust rating
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self) -> str:
        if self.company:
            return self.brand + " (" + self.company + ")"
        else:
            return self.brand


class Product(models.Model):
    product = models.CharField(
        max_length=128,
        validators=[MinLengthValidator(2, "Product name must be longer than two letters.")],
        unique=True,
    )
    brand = models.ForeignKey(Brand, null=True, on_delete=models.SET_NULL,
        related_name="product_brand")
    subcategory = models.ForeignKey(SubCategory, null=True, on_delete=models.SET_NULL,
        related_name="product_subcategory")
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL,
        related_name="product_owner")
    comments = models.ManyToManyField(settings.AUTH_USER_MODEL,
        through='Comment', related_name='product_comments')

    # Picture upload
    picture = models.BinaryField(null=True, blank=True, editable=True)
    content_type = models.CharField(max_length=256, null=True, blank=True,
        help_text='The MimeTypeof the file')


    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self) -> str:
        product_str = self.product
        if self.brand and self.subcategory:
            product_str = product_str + " by " + self.brand.brand + " (" + self.subcategory.category.category + ")"
        elif self.brand: 
            product_str = product_str + " by " + self.brand.brand
        elif self.subcategory:
            product_str = product_str + " (" + self.subcategory.subcategory + ", " + self.subcategory.category.category + ")"
        return product_str


class Comment(models.Model):
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be longer than three characters")]
    )

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Snippet
    def __str__(self):
        if len(self.text) < 17:
            return self.text
        return self.text[:13] + '...'


class Price(models.Model):
    price = models.DecimalField(max_digits=8, decimal_places=2)
    link = models.URLField(max_length=256)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="price_product")
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL,
        related_name="price_owner")

    date_observed = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self) -> str:
        price_str = str(self.price) + " (on " + str(self.date_observed) + ")"
        return price_str


class Feature(models.Model):
    feature = models.CharField(max_length=128)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="feature_product")
    class Meta:
        unique_together = ['feature', 'product']

    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self) -> str:
        return self.feature

cap/prcr/forms.py
from django import forms
from prcr.models import Feature, Product, Price, SubCategory
from django.core.files.uploadedfile import InMemoryUploadedFile
from prcr.humanize import naturalsize


class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=250, min_length=3, strip=True)


class FeatureCreateForm(forms.ModelForm):
    class Meta:
        model = Feature
        fields = ['feature']


class PriceCreateForm(forms.ModelForm):
    class Meta:
        model = Price
        fields = ['price', 'link']


class SubcategoryCreateForm(forms.ModelForm):
    class Meta:
        model = SubCategory
        fields = ['subcategory']


class ProductBrandCreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    upload_field_name = 'picture'

    class Meta:
        model = Product
        fields = ['product', 'subcategory', 'picture']  # Picture is manual

    # Validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < "+self.max_upload_limit_text+" bytes")
            
    # Convert uploaded File object to a picture
    def save(self, commit=True):
        instance = super(ProductBrandCreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture   # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()

        return instance


class ProductSubcategoryCreateForm(ProductBrandCreateForm):
    class Meta:
        model = Product
        fields = ['product', 'brand', 'picture']


class ProductUpdateForm(ProductBrandCreateForm):
    class Meta:
        model = Product
        fields = ['product', 'brand', 'subcategory', 'picture']


class ProductAddImageForm(ProductBrandCreateForm):
    class Meta:
        model = Product
        fields = ['picture']


# Source: https://www.dj4e.com/lessons/dj4e_ads1b
# https://docs.djangoproject.com/en/4.2/topics/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/4.2/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other

cap/prcr/templates/prcr/brand_form.html
{% extends "base_form.html" %}


{% block page_header %}
<h2 class="display-5 text-dark">Add new brand</h2>
{% endblock page_header %}


{% block inner_content %}
<input type="submit" value="Cancel" class="btn btn-lg btn-outline-danger"
    onclick="window.location.href='{% url 'prcr:brand_list'%}';return false;">
{% endblock inner_content %}

cap/prcr/templates/prcr/brand_list.html
{% extends "base_menu.html" %}


{% block page_header %}
<h2 class="display-5 text-dark">
    Browse brands</h2>
<p class="header-stat badge text-secondary mt-3 p-2 rounded-3 shadow-sm">
    {% if brand_count != 1 %} {{ brand_count }} brands<br><br><br>
    {% else %} {{ brand_count }} brand<br><br><br>{% endif %}
    {% if product_count != 1 %} {{ product_count }} products</p>
    {% else %} {{ product_count }} product</p>{% endif %}
<a class="header-link btn btn-md btn-outline-primary" href="{% url 'prcr:brand_create' %}">
    Add a brand<br> to pricer &raquo;</a>
{% endblock page_header %}


{% block content %}
{% if brand_list %}
{% for brand in brand_list %}
<section class="container-fluid mb-3">
    <h4 class="heading p-3 m-2 bg-light rounded-3 shadow-sm text-dark d-flex justify-content-between align-items-center">
        {{ brand }}
        <a href="{% url 'prcr:product_brand_create' brand.id %}"
            class="btn btn-sm btn-outline-secondary">
            Add {{ brand.brand }} products &raquo;</a>
    </h4>
</section>
<section class="container">
    {% if product_list %}
    <div class="row m-0">
        {% for product in product_list %}
        {% if product.brand.id == brand.id %}
        <a href="{% url 'prcr:product_detail' product.id %}" class="link-style col-md-6">
            <div class="cards card p-3 row g-0 border rounded-3 overflow-hidden mb-4 shadow-sm h-md-250 position-relative">
                <div class="row g-0 card-header flex-md-row">
                    <h5 class="pt-2 text-dark">
                    {{ product.product }}</h5>
                    </div>
                <div class="card-body d-flex justify-content-between align-items-center">
                    <p class="card-text mb-auto text-dark text-small">
                        {% if feature_list %} <span class="text-muted">&#9679;</span>
                        {% for feature in feature_list %}{% if feature.product.id == product.id %}
                        {{ feature }} &raquo;
                        {% endif %}{% endfor %}{% endif %}
                    </p>
                    {% if product.content_type %}
                    <img src="{% url 'prcr:product_picture' product.id %}" class="card-pic rounded-3 ms-3">
                    {% endif %}
                </div>
            </div>
        </a>
        {% endif %}
        {% endfor %}
    </div>
    {% endif %}
</section>
{% endfor %}
{% else %}
<section class="section p-1 m-3 bg-light rounded-3">
    <div class="no-content container-fluid">
        <p class="p-3 m-2 text-danger">There are no brands yet in Pricer<br>
            Add categories, subcategories and brands before creating a product</p>
    </div>
</section>
{% endif %}
{% endblock content %}


{% block footer %}
    <p>Copyright or something</p>
{% endblock footer %}

cap/prcr/templates/prcr/category_form.html
{% extends "base_form.html" %}


{% block page_header %}
<h2 class="display-5 text-dark">Add new category</h2>
{% endblock page_header %}


{% block inner_content %}
<input type="submit" value="Cancel" class="btn btn-lg btn-outline-danger"
    onclick="window.location.href='{% url 'prcr:main_list'%}';return false;">
{% endblock inner_content %}

cap/prcr/templates/prcr/comment_delete_form.html
{% extends "base_bootstrap.html" %}

{% block page_header %}
<h3>Delete Comment</h3>
{% endblock page_header %}

{% block content %}
<p>Are you sure you want to delete</p>
<p>{{ comment.text }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <a href="{% url 'prcr:product_detail' comment.product.id %}"
    class="btn btn-danger">Cancel</a>
</form>
{% endblock content %}

cap/prcr/templates/prcr/feature_form.html
{% extends "base_form.html" %}


{% block page_header %}
<h3 class="display-6 text-dark">Add a new feature to<br>
    <span class="text-primary display-3"> {{ product.product }} </span>
    <span class="text-small"> ({{ product.brand.brand }}) </span></h3>
{% endblock page_header %}


{% block inner_content %}
<input type="submit" value="Cancel" class="btn btn-lg btn-outline-danger"
    onclick="window.location.href='{% url 'prcr:product_detail' product.id %}';return false;">
{% endblock inner_content %}

cap/prcr/templates/prcr/main_list.html
{% extends "base_menu.html" %}


{% block page_header %}
<h2 class="display-5 text-dark">
    Browse<br>categories</h2>
<p class="header-stat badge text-dark mt-3 p-2 rounded-3 shadow-sm">
    {% if category_count != 1 %} {{ category_count }} categories<br><br>
    {% else %} {{ category_count }} category<br><br>{% endif %}
    {% if subcategory_count != 1 %} {{ subcategory_count }} subcategories<br><br>
    {% else %} {{ subcategory_count }} subcategory<br><br>{% endif %}
    {% if product_count != 1 %} {{ product_count }} products<br><p>
    {% else %} {{ product_count }} product<br></p>{% endif %}
<a class="header-link btn btn-md btn-outline-primary"
    href="{% url 'prcr:category_create' %}">
    Add a category<br>to Pricer &raquo;</a>
{% endblock page_header %}


{% block content %}
{% if category_list %}
{% for category in category_list %}
<section class="no-bg p-1 m-3 bg-light rounded-3">
    <div class="container-fluid">
        <h4 class="heading p-3 mb-3 bg-light rounded-3 shadow-sm text-dark d-flex justify-content-between align-items-center">
        {{ category.category }}
        <a href="{% url 'prcr:subcategory_create' category.id %}"
            class="btn btn-sm btn-outline-secondary">
            Add a subcategory to {{ category.category }} &raquo;</a></h4>
        {% if subcategory_list %}
        <ul>
            {% for subcategory in subcategory_list %}
            {% if subcategory.category.id == category.id %}
            <li class="plain-list">
                <a href="{% url 'prcr:product_list' subcategory.id %}" class="link-style">
                    <div class="cards p-2 mb-3 rounded 3 shadow-sm text-small">
                    <strong>{{ subcategory.subcategory }}</strong>
                    {% if product_list %}<span class="text-muted">
                        {% for product in product_list %}
                        {% if product.subcategory.id == subcategory.id %}
                        {% if forloop.counter < 30 %}
                        &#9679; {{ product.product }} ({{ product.brand.brand }})
                        {% endif %}
                        {% endif %}
                        {% endfor %}</span>
                    {% endif %}
                    </div>
                </a>
            </li>
            {% endif %}
            {% empty %}
            <p class="p-3 m-2 text-danger">This category has no subcategories. Add one.</p>
            {% endfor %}
        </ul>
        {% endif %}            
    </div>
</section>
{% endfor %}
{% else %}
<section class="section p-1 m-3 bg-light rounded-3">
    <div class="no-content container-fluid">
        <p class="p-3 m-2 text-danger">There are no categories yet in Pricer.<br>
            Add categories, subcategories and brands before creating a product.</p>
    </div>
</section>
{% endif %}
{% endblock content %}


{% block footer %}
    <p>Copyright or something</p>
{% endblock footer %}

cap/prcr/templates/prcr/price_form.html
{% extends "base_form.html" %}


{% block page_header %}
<h3 class="display-6 text-dark">Add a new price link to<br>
    <span class="text-primary display-3"> {{ product.product }} </span>
    <span class="text-small"> ({{ product.brand.brand }}) </span></h3>
{% endblock page_header %}


{% block inner_content %}
<input type="submit" value="Cancel" class="btn btn-lg btn-outline-danger"
    onclick="window.location.href='{% url 'prcr:product_detail' product.id %}';return false;">
{% endblock inner_content %}

cap/prcr/templates/prcr/product_add_image_form.html
{% extends "base_form_w_img.html" %}


{% block page_header %}
<h3 class="display-6 text-dark">Add an image of the<br>
    <span class="text-primary display-3"> {{ product.product }} </span>
    <span class="text-small"> ({{ product.brand.brand }}) </span></h3>
{% endblock page_header %}


{% block inner_content %}
<input type="submit" value="Cancel" class="btn btn-lg btn-outline-danger"
    onclick="window.location.href='{% url 'prcr:product_detail' product.id %}';return false;">
{% endblock inner_content %}

cap/prcr/templates/prcr/product_detail.html
{% extends "base_menu.html" %}
{% load humanize %}
{% block head %}
<style>
    .overlay{
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: 10;
        display: none;
        background-color: rgba(0,0,0,0.5);
    }
</style>
{% endblock head %}


{% block page_header %}
<h2 class="display-6 text-primary"> {{ product.product }} <br>
    <span class="fs-5 text-muted"> {{ product.brand }} </span>
</h2>
<p class="header-stat badge text-secondary mt-3 p-2 rounded-3 shadow-sm">
    updated<br><br>{{ product.natural_updated }}</p>
<p>{% if product.owner == user %}
    <a href="{% url 'prcr:product_update' product.id %}"
        class="btn btn-md btn-outline-secondary mt-5">Edit &raquo;</a>
{% endif %}</p>
{% endblock page_header %}


{% block content %}
{% if product.content_type %}
<div id="overlay" class="overlay" onclick="document.getElementById('overlay').style.display = 'none';">
    <img id="overlay-image" src="{% url 'prcr:product_picture' product.id %}">
</div>
{% endif %}
<div class="main p-1 m-3 bg-light rounded-3 shadow-sm">
    <div class="container">
        <section class="row">
            <div class="col-7 mt-3">
                <h5>Product features</h5><p class="fs-6 text-dark">
                    {% if feature_list %}{% for feature in feature_list %}{{ feature }} &raquo; 
                    {% endfor %}{% else %}The feature list is empty{% endif %}</p>
                <a href="{% url 'prcr:feature_create' product.id %}"
                    class="btn btn-sm btn-outline-secondary text-start mb-3">
                    Add a product feature &raquo;</a><br>
                {% if price_list %}
                <a href="{{ lowest_price.link }}" target="_blank"
                    class="btn btn-md btn-outline-success text-dark text-start mt-3">
                    <span class="fs-5">Best price ${{ lowest_price.price|intcomma }} &raquo;</span><br>
                    <span class="text-secondary">{{ lowest_price.domain }} 
                        {{ lowest_price.date_observed|naturalday }}</span></a><br>
                <a href="{{ highest_price.link }}" target="_blank"
                    class="btn btn-md btn-outline-danger text-dark text-start mt-3">
                    <span class="fs-5">Worst price ${{ highest_price.price|intcomma }} &raquo;</span><br>
                    <span class="text-secondary">{{ highest_price.domain }} 
                    {{ highest_price.date_observed|naturalday }}</span></a>
                {% else %}<p>Price list is empty{% endif %}</p>
                <a href="{% url 'prcr:price_create' product.id %}"
                    class="btn btn-sm btn-outline-secondary text-start mb-3">
                    Did you see an offer online? Add a price link &raquo;</a>
            </div>
            <div class="col-5">
                {% if product.content_type %}
                <img src="{% url 'prcr:product_picture' product.id %}"
                    id="product-profile-pic" class="rounded-3 mt-3"
                    onclick="document.getElementById('overlay').style.display = 'block';">
                {% else %}
                <div id="product-profile-no-pic-div" class="container-fluid rounded-3 mt-3">
                    <a href="{% url 'prcr:product_add_image' product.id %}"
                        id="product-profile-no-pic" class="btn btn-lg btn-outline-dark">
                        <br>Add an image</a> 
                </div>
                {% endif %}
            </div>
        </section>
        <section class="row">
            <div class="product-profile col-11 m-3">
                {{ price_chart|safe }}
            </div>
        </section>
        <section class="row">
            <div class="col-5 mt-2">
                <h5>Price history</h5>
                <a href="{% url 'prcr:price_create' product.id %}"
                    class="btn btn-sm btn-outline-secondary text-start mb-3">
                    Did you see an offer online? Add a price link &raquo;</a>
                {% if price_list %}{% for price in price_list %}
                {% if price.price == lowest_price.price %}
                <p><a href="{{ price.link }}" class="btn btn-md btn-outline-success text-dark"
                    target="_blank">
                    <strong>Best offer &#9679; ${{ price.price|intcomma }}</strong>
                    &#9679; {{ price.domain }}
                    &#9679; {{ price.natural_date_observed }} </a></p>
                {% else %}
                <p><a href="{{ price.link }}" class="btn btn-sm btn-outline-dark"
                    target="_blank">
                    <strong>${{ price.price|intcomma }}</strong>
                    &#9679; {{ price.domain }}
                    &#9679; {{ price.natural_date_observed }} </a></p>
                {% endif %}{% endfor %}{% endif %}
            </div>
            <div class="comments col-5 mt-2">
                <h5>Comments</h5>
                {% if user.is_authenticated %}
                <p>
                {% load crispy_forms_tags %}
                <form method="post" action="{% url 'prcr:post_comment' product.id %}">
                    {% csrf_token %}
                    {{ comment_form|crispy }}
                    <input type="submit" value="Submit">
                </form>
                </p>
                {% endif %}
                {% if comments %}{% for comment in comments %}
                <p> {{ comment.text }} ({{ comment.updated_at|naturaltime }})
                    {% if user == comment.owner %}
                    <a href="{% url 'prcr:detele_comment' comment.id %}"><i class="fa fa-trash"></i></a>
                    {% endif %}
                </p>
                {% endfor %}{% endif %}
            </div>
        </section>
    </div>
</div>
{% endblock content %}


{% block footer %}
<p><a href="{% url 'prcr:product_list' product.subcategory_id %}"
    class="btn btn-sm btn-outline-secondary m-2">
    Back to browsing {{ product.subcategory }} &raquo;</a></p>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
{% endblock footer %}

cap/prcr/templates/prcr/product_list.html
{% extends "base_menu.html" %}


{% block page_header %}
{% load humanize %}
<h2 class="display-5 text-dark"> {{ subcategory.subcategory }} </h2>
<p class="header-stat badge text-secondary mt-3 p-2 rounded-3 shadow-sm">
    {% if filtered_products %} {% if filtered_products|length == 1 %}
    1 product in {{ subcategory.subcategory|lower }}
    {% else %}{{filtered_products|length}} {{ subcategory.subcategory|lower }}
    {% endif %}{% else %} 0 {{ subcategory.subcategory|lower }}
    {% endif %}</p>
<p><a class="btn btn-md btn-outline-primary mt-3" 
    href="{% url 'prcr:product_subcategory_create' subcategory.id %}">
    Add a new product to {{ subcategory|lower }} &raquo;</a></p>
{% endblock page_header %}


{% block content %}
{% for product in filtered_products %}
<section class="product cards p-2 pt-3 m-3 bg-light rounded-3 shadow-sm">
    <div class="container-fluid d-flex justify-content-between">
        <div><a href="{% url 'prcr:product_detail' product.id %}" class="link-style">
            <p>{{ product.product }}
                {% for brand in brands %}{% if brand.id == product.brand_id %}
                <span class="small text-muted">({{ brand.brand }})
                {% endif %}{% endfor %}
                {% if product_lowest_price_list %}{% for product_id, price in product_lowest_price_list %}
                {% if product_id == product.id %}
                &#9679; Lowest price offer ${{ price|intcomma }},
                {% endif %}{% endfor %}{% endif %}</span></p>
            <p class="small text-dark">
            {% if feature_list %}{% for feature in feature_list %}{% if feature.product_id == product.id %}
            {{ feature }} &raquo; {% endif %}{% endfor %}{% endif %}</p></a>
            {% if product.owner_id == user.id %}
            <p><a class="btn btn-sm btn-outline-secondary mt-1 text-muted" 
                href="{% url 'prcr:product_update' product.id %}">
                Edit this product &raquo;</a></p>
            {% endif %}
        </div>
        {% if product.content_type %}
        <img class="product-pic rounded-3 me-1" 
            src="{% url 'prcr:product_picture' product.id %}">
        {% else %}
        <a href="{% url 'prcr:product_add_image' product.id %}"
            class="product-no-pic link-style outline-secondary rounded-3 me-1">
            Add an image</a>
        {% endif %}
    </div>
</section>
{% empty %}
<section class="section p-3 m-3 bg-light rounded-3">
    <div class="no-content text-danger">
        <p>There are no products yet in this subcategory.</p>
    </div>
</section>
{% endfor %}
{% endblock content %}


{% block footer %}
    <p>Copyright or something</p>
{% endblock footer %}